version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=challengebackend
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  challengebackend:
    build: . 
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - SERVER_PORT=8081
      - DATABASE_URL=jdbc:mysql://db:3306/challengebackend?autoReconnect=true
      - "SPRING_PROFILES_ACTIVE=prod"
volumes:
  db:
    driver: local